# Change baseurl before deploy
baseurl = "https://blog.onani0721.top"
languageCode = "en"
title = "Epiphany0v0"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-tw"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "Epiphany0v0"

[pagination]
pagerSize = 5
